config/routes.rb
Rails.application.routes.draw do

   root 'openings#index'

  resources :openings
end

app/models/opening.rb
class Opening < ActiveRecord::Base
    belongs_to :supervisor
    validates :supervisor_id, presence: true
    validates :position, presence: true
    validates :replacing, presence: true
    validates :shift, presence: true
    validates :schedule, presence: true
    validates :status, presence: true
    validates :emp, presence: true
    validates :reason, presence: true
    validates :action, presence: true
    validates :dept, presence: true
end

app/models/supervisor.rb
class Supervisor < ActiveRecord::Base
    has_many :openings
    before_save {self.email = email.downcase}
  validates :name, presence: true, length: {minimum: 5, maximum: 50}
  validates :email, presence: true, 
                    uniqueness: {case_sensitive: false}
  validates :plant, presence: true, length: {minimum: 5, maximum: 30}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/openings_controller.rb
class OpeningsController < ApplicationController
    def index
        @openings = Opening.all
    end
    
    def openings
        @openings = Opening.all
    end
    
    def show
        @openings = Opening.find(params[:id])    
    end
    
    
    def new
        @openings = Opening.new
    end
    
    def create
        @opening = Opening.create(openings_param)
        @opening.supervisor = Supervisor.find(1)
        
        if @opening.save
            flash[:success] = "Request created sucessfully!"
            redirect_to openings_path
            
        else
            render :new
        end
    end
    
    def edit
        @opening = Opening.edit(params[:id])
    end
    
    def update
       @opening = Opening.find(params[:id])
       
        if @opening.update(openings_param)
            flash[:success] = "Request created sucessfully!"
            redirect_to openings_path
        else
            render :edit
        end
    end
    
    private 
    
    def openings_param
        params.require(:opening).permit(:position, :replacing, :emp, :reason, :action, :shift, :dept, :schedule, :status)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/openings_helper.rb
module OpeningsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div class= "container center">

<%= yield %>

</div>
</body>
</html>

app/views/openings/index.html.erb
<h1>Vacancies</h1>

</hr>
    <div class = "row center">
        <table class="table table-striped" >
        <thead></thead>
            <tr>
                <th>id</th>
                <th>position</th>
                <th>department</th>
                <th>schedule</th>
                <th>supervisor</th>
                <th>created</th>
            </tr>
        <thead/>
        <tbody>
        <% @openings.each do |t| %>
            <td><%=link_to t.id, opening_path(t) %></td>
            <td><%=t.position %></td>
            <td><%=t.dept %></td>
            <td><%=t.schedule %></td>
            <td><%=t.supervisor.name%></td>
            <td><%=t.created_at.strftime("%b %d %Y")%></td>
         </tbody> 
        <% end %>
        
        </table>
    </div>

app/views/openings/show.html.erb
<div class= "row center">
    <div class= "col-md-8 col-md-offset-2 well">
        <%= form_for @openings do |f| %>
           <%= f.label :position %>
           <%= f.text_field :position %>
           
           <%= f.label :replacing %>
           <%= f.text_field :replacing%>
           
           <%= f.label :employee%>
           <%= f.text_field :emp%>
           
           <%= f.label :reason%>
           <%= f.text_field :reason%>
           
           <%= f.label :action%>
           <%= f.text_field :action%>
           
           <%= f.label :shift%>
           <%= f.text_field :shift%>
           
           <%= f.label :department %>
           <%= f.text_field :dept%>
           
           <%= f.label :schedule%>
           <%= f.text_field :schedule%>
           
           <%= f.label :status%>
           <%= f.text_field :status%>
           
           <%=f.submit 'Update Request', class: "btn btn-primary" %>
        <% end %>
    </div>
</div>